# Generated by Django 3.0.5 on 2020-10-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_name', models.CharField(max_length=30)),
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField()),
            ],
        ),
    ]
